function imprimeEvento(nome, t_val, x_val)
    deg2rad = pi/180;
    fprintf('\n--- EVENTO %s ---\n', upper(nome));
    fprintf(['Tempo: %7.4f s | Longitude: %8.4f km |' ...
        ' Altitude: %8.4f km | Velocidade: %7.4f m/s |' ...
        ' Path: %6.4f deg\n'], ...
        t_val, x_val(1)/1000, x_val(2)/1000, x_val(3), x_val(4)/deg2rad);
end